
/*Configuration register in system controller */
#define SHIKHARA_SYS_CTRL_DMAC_CONFIG_REG     (SHIKHARA_SYS_CTRL_BASEADDR + 0x068)
#define SHIKHARA_SYS_CTRL_DMAC_CONFIG_RESET   (SHIKHARA_SYS_CTRL_BASEADDR + 0x044)
/*DMA Registers*/
#define SDMAC2_INTEN          (SHIKHARA_DMAC2_SBASE + 0x020)
#define SDMAC2_INTSTATUS      (SHIKHARA_DMAC2_SBASE + 0x028)
#define SDMAC2_ES             (SHIKHARA_DMAC2_SBASE + 0x024)
#define SDMAC2_INTCLR         (SHIKHARA_DMAC2_SBASE + 0x02c)
#define SDMAC2_FSRD           (SHIKHARA_DMAC2_SBASE + 0x030)
#define SDMAC2_FSRC           (SHIKHARA_DMAC2_SBASE + 0x034)
#define SDMAC2_FTRD           (SHIKHARA_DMAC2_SBASE + 0x038)
#define SDMAC2_FTCH0          (SHIKHARA_DMAC2_SBASE + 0x040)
#define SDMAC2_CHPC0          (SHIKHARA_DMAC2_SBASE + 0x104)
#define SDMAC2_CHST0          (SHIKHARA_DMAC2_SBASE + 0x100)

#define SDMAC2_DBGSTATUS     (SHIKHARA_DMAC2_SBASE + 0xD00)
#define SDMAC2_DBGCMD         (SHIKHARA_DMAC2_SBASE + 0xD04)
#define SDMAC2_DBGINST0       (SHIKHARA_DMAC2_SBASE + 0xD08)
#define SDMAC2_DBGINST1       (SHIKHARA_DMAC2_SBASE + 0xD0C)

/*Non Secure DMA Registers */
#define NSDMAC2_INTEN          (SHIKHARA_DMAC2_NSBASE + 0x020)
#define NSDMAC2_INTSTATUS      (SHIKHARA_DMAC2_NSBASE + 0x028)
#define NSDMAC2_ES             (SHIKHARA_DMAC2_NSBASE + 0x024)
#define NSDMAC2_INTCLR         (SHIKHARA_DMAC2_NSBASE + 0x02c)
#define NSDMAC2_FSRD           (SHIKHARA_DMAC2_NSBASE + 0x030)
#define NSDMAC2_FSRC           (SHIKHARA_DMAC2_NSBASE + 0x034)
#define NSDMAC2_FTRD           (SHIKHARA_DMAC2_NSBASE + 0x038)
#define NSDMAC2_FTCH0          (SHIKHARA_DMAC2_NSBASE + 0x040)
#define NSDMAC2_CHPC0          (SHIKHARA_DMAC2_NSBASE + 0x104)
#define NSDMAC2_CHST0          (SHIKHARA_DMAC2_NSBASE + 0x100)

#define NSDMAC2_DBGSTATUS     (SHIKHARA_DMAC2_NSBASE + 0xD00)
#define NSDMAC2_DBGCMD         (SHIKHARA_DMAC2_NSBASE + 0xD04)
#define NSDMAC2_DBGINST0       (SHIKHARA_DMAC2_NSBASE + 0xD08)
#define NSDMAC2_DBGINST1       (SHIKHARA_DMAC2_NSBASE + 0xD0C)

/*DMAC0 NS registers*/
#define NSDMAC0_MNGST          (SHIKHARA_DMAC0_NSBASE + 0x000)
#define NSDMAC0_INTEN          (SHIKHARA_DMAC0_NSBASE + 0x020)
#define NSDMAC0_INTSTATUS      (SHIKHARA_DMAC0_NSBASE + 0x028)
#define NSDMAC0_ES             (SHIKHARA_DMAC0_NSBASE + 0x024)
#define NSDMAC0_INTCLR         (SHIKHARA_DMAC0_NSBASE + 0x02c)
#define NSDMAC0_FSRD           (SHIKHARA_DMAC0_NSBASE + 0x030)
#define NSDMAC0_FSRC           (SHIKHARA_DMAC0_NSBASE + 0x034)
#define NSDMAC0_FTRD           (SHIKHARA_DMAC0_NSBASE + 0x038)
#define NSDMAC0_FTCH0          (SHIKHARA_DMAC0_NSBASE + 0x040)
#define NSDMAC0_CHPC0          (SHIKHARA_DMAC0_NSBASE + 0x104)
#define NSDMAC0_CHST0          (SHIKHARA_DMAC0_NSBASE + 0x100)

#define NSDMAC0_FTCH1          (SHIKHARA_DMAC0_NSBASE + 0x044)
#define NSDMAC0_CHPC1          (SHIKHARA_DMAC0_NSBASE + 0x10C)
#define NSDMAC0_CHST1          (SHIKHARA_DMAC0_NSBASE + 0x108)

#define NSDMAC0_LPCH0          (SHIKHARA_DMAC0_NSBASE + 0x40C)
#define NSDMAC0_LPCH1          (SHIKHARA_DMAC0_NSBASE + 0x42C)

#define NSDMAC0_SARCH0          (SHIKHARA_DMAC0_NSBASE + 0x400)
#define NSDMAC0_DARCH0          (SHIKHARA_DMAC0_NSBASE + 0x404)
#define NSDMAC0_SARCH1          (SHIKHARA_DMAC0_NSBASE + 0x420)
#define NSDMAC0_DARCH1          (SHIKHARA_DMAC0_NSBASE + 0x424)

#define NSDMAC0_DBGSTATUS     (SHIKHARA_DMAC0_NSBASE + 0xD00)
#define NSDMAC0_DBGCMD         (SHIKHARA_DMAC0_NSBASE + 0xD04)
#define NSDMAC0_DBGINST0       (SHIKHARA_DMAC0_NSBASE + 0xD08)
#define NSDMAC0_DBGINST1       (SHIKHARA_DMAC0_NSBASE + 0xD0C)

