#include <common.h>
#include <command.h>
#include <asm/io.h>
#include <i2c.h>
#include <asm/arch/shikhara_i2c.h>
#include <asm/types.h>
#include <asm/arch/shikhara_mipi_csi.h>
#include <asm/arch/shikhara_mipi_csi_bridge.h>
#include <asm/arch/shikhara_map.h>
#include <asm/arch/shikhara_gpio.h>
#include <malloc.h>
#include <asm/arch/dma.h>

#define TZ 0xD456C108

#define OV5640_I2C_SLAVE_ADDR		0x3c
static int AE_low, AE_high, AE_Target = 52;
static int preview_sysclk, preview_HTS, preview_sysclk;
static int XVCLK = 2400;

#define OV5640_CHIP_ID_HIGH_BYTE	0x300A
#define OV5640_CHIP_ID_LOW_BYTE		0x300B
#define OV5640_CAMERA_I2C_BUS_NO	2
void rgbconversion(void);
void copy_imagestohdmi(void);
struct reg_value {
	u16 u16RegAddr;
	u8 u8Val;
	u8 u8Mask;
	u32 u32Delay_ms;
};

#define SECURE_DMA      	1
#define BUF_LEN         	1024
#define MC_CODE_LEN     	64
#define NUMBER_OF_BUFFERS 	10
#define DMA_CODE1_L      	10




#if 1
static unsigned int dma_code_ns[NUMBER_OF_BUFFER_DESCRIPTORS][10] ={
/*
        ;;The below microcode is generated by the code.
        DMAMOV CCR SB16 SP7 SS64 DB16 DP7 DS64
        DMAMOV   SAR, 0x53AFE068
        DMAMOV   DAR, 0x53AFe470
        DMALP LC1, 8 ;loop count is calculated for 1024 byte (1024/((64/8)*16)).
        DMALD
        DMAST
        DMALPEND
        DMASEV E1
        DMAEND
*/

	{0x47F901BC, 0x00BC01FE, 0x11000000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834}, // CSI frame Buffer Address is 0x11000000 i.e 3rd parameter in Generated Hex code 
	{0x47F901BC, 0x00BC01FE, 0x11100000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834}, // HDMI Frame Buffer(Destination) is Two MSBs in 3rd parameter and
	{0x47F901BC, 0x00BC01FE, 0x11200000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834}, // Two LSBs in 4th parameter i.e 0x01200000 (order is 0x<2 LSBs in 3rd Param><2 MSBs in 4th Param>   
	{0x47F901BC, 0x00BC01FE, 0x11300000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x11400000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x11500000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x11600000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x11700000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x11800000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x11900000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x11a00000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x11b00000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x11c00000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x11d00000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x11e00000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x11f00000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x12000000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x12100000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x12200000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x12300000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x12400000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x12500000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x12600000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x12700000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x12800000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x12900000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x12a00000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x12b00000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x12c00000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x12d00000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},
	{0x47F901BC, 0x00BC01FE, 0x12e00000, 0x000002BC, 0xC7200120, 0x08041122, 0x0638023C, 0xFF000834},



};


static int dmatransfer_csi_hdmi (int frame_number)
{
        unsigned int i,j,st;
        unsigned int data, errors = 0;
        volatile unsigned int * address;
	volatile unsigned int *mc = (unsigned int *)0x4000;
        int pass = TRUE;
#if 0
        //Reset DMAC
        writel(0xC,SHIKHARA_SYS_CTRL_DMAC_CONFIG_RESET);
        mdelay(10);

        /* Change DMA Manager to NS state */
        writel(0x400,SHIKHARA_SYS_CTRL_DMAC_CONFIG_REG);
        udelay(10);
        /*Release reset for DMAC*/
        writel(0x0,SHIKHARA_SYS_CTRL_DMAC_CONFIG_RESET);
#endif     

        //write dma programm at c"

        address = mc ;
        for (i=0;i<DMA_CODE1_L;i++)
        {
                *address = dma_code_ns[frame_number][i];
                address = address + 1;
        }

        // DBGINST0: DMAGO instruction on channel 0
        writel(0x02,NSDMAC2_INTEN);
        while(readl(NSDMAC2_DBGSTATUS));
        writel(0xa20000,NSDMAC2_DBGINST0);
        // DBGINST1: address of first intruction in the program
        writel(mc,NSDMAC2_DBGINST1);
        // Enables the interrupt 1
        // DBGCMD: instructs the DMA to execute the instruction
        writel(0x00,NSDMAC2_DBGCMD);
        /* Generate Non-Secure Mem-Mem request for DMA2  */
        writel(0x1000,SHIKHARA_SYS_CTRL_DMAC_CONFIG_REG);
        // wait for interrupt
        while (errors < 1000)
        {   st=readl(NSDMAC2_INTSTATUS)|| readl(NSDMAC2_ES);
                if(st) // Poll for interrupts
                        break;
                errors +=1;
        }
        dbg("Interrupt Status : 0x%X  and error %d\n",st,errors);
        if(errors)
        {
                printf("FAILED: Error occurs during data transfers\n");
        }

        errors = 0;
        //Clear interrupt
        writel(0x02,NSDMAC2_INTCLR);
        writel(0x00,NSDMAC2_INTEN);
#if 0
	if (pass)
                printf("PASSED: Data is transferred\n\n");
        else
                printf("FAILED: Data is not transferred\n\n");
#endif
        return pass;
}

#endif



static struct reg_value ov5640_init_setting_30fps_VGA[] = {

#ifdef HDMI_640_480
	{0x3103, 0x11, 0, 5}, {0x3008, 0x82, 0, 0}, {0x3008, 0x42, 0, 0}, 
	{0x3103, 0x03, 0, 0}, {0x3017, 0x00, 0, 0}, {0x3018, 0x00, 0, 0},  
#ifdef CONFIG_OV5640_RGB565
	{0x3034, 0x18, 0, 0}, {0x3035, 0x12, 0, 0}, {0x3036, 0x38, 0, 0}, 
	{0x3037, 0x12, 0, 0}, {0x3108, 0x01, 0, 0}, {0x3630, 0x36, 0, 0}, 
#endif

#ifdef CONFIG_OV5640_RGB888
	{0x3034, 0x18, 0, 0}, {0x3035, 0x12, 0, 0}, {0x3036, 0x38, 0, 0}, 
	{0x3037, 0x12, 0, 0}, {0x3108, 0x01, 0, 0}, {0x3630, 0x36, 0, 0}, 
#endif
	{0x3631, 0x0e, 0, 0}, {0x3632, 0xe2, 0, 0}, {0x3633, 0x12, 0, 0}, 
	{0x3621, 0xe0, 0, 0}, {0x3704, 0xa0, 0, 0}, {0x3703, 0x5a, 0, 0}, 
	{0x3715, 0x78, 0, 0}, {0x3717, 0x01, 0, 0}, {0x370b, 0x60, 0, 0}, 
	{0x3705, 0x1a, 0, 0}, {0x3905, 0x02, 0, 0}, {0x3906, 0x10, 0, 0}, 
	{0x3901, 0x0a, 0, 0}, {0x3731, 0x12, 0, 0}, {0x3600, 0x08, 0, 0}, 
	{0x3601, 0x33, 0, 0}, {0x302d, 0x60, 0, 0}, {0x3620, 0x52, 0, 0}, 
	{0x371b, 0x20, 0, 0}, {0x471c, 0x50, 0, 0}, {0x3a13, 0x43, 0, 0}, 
	{0x3a18, 0x00, 0, 0}, {0x3a19, 0xf8, 0, 0}, {0x3635, 0x13, 0, 0}, 
	{0x3636, 0x03, 0, 0}, {0x3634, 0x40, 0, 0}, {0x3622, 0x01, 0, 0}, 
	{0x3c01, 0x34, 0, 0}, {0x3c04, 0x28, 0, 0}, {0x3c05, 0x98, 0, 0},  
	{0x3c06, 0x00, 0, 0}, {0x3c07, 0x08, 0, 0}, {0x3c08, 0x00, 0, 0}, 
	{0x3c09, 0x1c, 0, 0}, {0x3c0a, 0x9c, 0, 0}, {0x3c0b, 0x40, 0, 0}, 
	{0x3820, 0x41, 0, 0}, {0x3821, 0x07, 0, 0}, {0x3814, 0x31, 0, 0}, 
	{0x3815, 0x31, 0, 0}, {0x3800, 0x00, 0, 0}, {0x3801, 0x00, 0, 0}, 
	{0x3802, 0x00, 0, 0}, {0x3803, 0x04, 0, 0}, {0x3804, 0x0a, 0, 0}, 
	{0x3805, 0x3f, 0, 0}, {0x3806, 0x07, 0, 0}, {0x3807, 0x9b, 0, 0}, 
	{0x3808, 0x02, 0, 0}, {0x3809, 0x80, 0, 0}, {0x380a, 0x01, 0, 0},
	{0x380b, 0xe0, 0, 0}, {0x380c, 0x07, 0, 0}, {0x380d, 0x68, 0, 0}, 
	{0x380e, 0x03, 0, 0}, {0x380f, 0xd8, 0, 0}, {0x3810, 0x00, 0, 0}, 
	{0x3811, 0x10, 0, 0}, {0x3812, 0x00, 0, 0}, {0x3813, 0x06, 0, 0}, 
	{0x3618, 0x00, 0, 0}, {0x3612, 0x29, 0, 0}, {0x3708, 0x66, 0, 0}, 
	{0x3709, 0x12, 0, 0}, {0x370c, 0x03, 0, 0}, {0x3a02, 0x03, 0, 0}, 
	{0x3a03, 0xd8, 0, 0}, {0x3a08, 0x01, 0, 0}, {0x3a09, 0x27, 0, 0}, 
	{0x3a0a, 0x00, 0, 0}, {0x3a0b, 0xf6, 0, 0}, {0x3a0e, 0x03, 0, 0}, 
	{0x3a0d, 0x04, 0, 0}, {0x3a14, 0x03, 0, 0}, {0x3a15, 0xd8, 0, 0}, 
	{0x4001, 0x02, 0, 0}, {0x4004, 0x02, 0, 0}, {0x4050, 0x6e, 0, 0}, 
	{0x4051, 0x8f, 0, 0}, {0x3000, 0x00, 0, 0}, {0x3002, 0x1c, 0, 0}, 
	{0x3004, 0xff, 0, 0}, {0x3006, 0xc3, 0, 0}, {0x300e, 0x45, 0, 0},

#ifdef CONFIG_OV5640_RGB565
	{0x302e, 0x08, 0, 0}, {0x4300, 0x60, 0, 0}, {0x501f, 0x01, 0, 0}, 
#endif

#ifdef CONFIG_OV5640_RGB888
	{0x302e, 0x08, 0, 0}, {0x4300, 0x22, 0, 0}, {0x501f, 0x01, 0, 0}, 
#endif
	{0x5684, 0x05, 0, 0}, {0x5685, 0x00, 0, 0}, {0x5686, 0x03, 0, 0}, 
	{0x5687, 0xc0, 0, 0}, {0x4713, 0x03, 0, 0}, {0x4407, 0x04, 0, 0}, 
	{0x440e, 0x00, 0, 0}, {0x460b, 0x35, 0, 0}, {0x460c, 0x22, 0, 0}, 
	{0x4837, 0x44, 0, 0}, {0x3824, 0x02, 0, 0}, {0x5000, 0xa7, 0, 0}, 
	{0x5001, 0xa3, 0, 0}, {0x5180, 0xff, 0, 0}, {0x5181, 0xf2, 0, 0}, 
	{0x5182, 0x00, 0, 0}, {0x5183, 0x14, 0, 0}, {0x5184, 0x25, 0, 0}, 
	{0x5185, 0x24, 0, 0}, {0x5186, 0x09, 0, 0}, {0x5187, 0x09, 0, 0}, 
	{0x5188, 0x09, 0, 0}, {0x5189, 0x75, 0, 0}, {0x518a, 0x54, 0, 0}, 
	{0x518b, 0xe0, 0, 0}, {0x518c, 0xb2, 0, 0}, {0x518d, 0x42, 0, 0}, 
	{0x518e, 0x3d, 0, 0}, {0x518f, 0x56, 0, 0}, {0x5190, 0x46, 0, 0}, 
	{0x5191, 0xf8, 0, 0}, {0x5192, 0x04, 0, 0}, {0x5193, 0x70, 0, 0}, 
	{0x5194, 0xf0, 0, 0}, {0x5195, 0xf0, 0, 0}, {0x5196, 0x03, 0, 0}, 
	{0x5197, 0x01, 0, 0}, {0x5198, 0x04, 0, 0}, {0x5199, 0x12, 0, 0}, 
	{0x519d, 0x82, 0, 0}, {0x519e, 0x38, 0, 0}, {0x5381, 0x1e, 0, 0}, 
	{0x5382, 0x5b, 0, 0}, {0x5383, 0x08, 0, 0}, {0x5384, 0x0a, 0, 0}, 
	{0x5385, 0x7e, 0, 0}, {0x5386, 0x88, 0, 0}, {0x5387, 0x7c, 0, 0}, 
	{0x5388, 0x6c, 0, 0}, {0x5389, 0x10, 0, 0}, {0x538a, 0x01, 0, 0}, 
	{0x538b, 0x98, 0, 0}, {0x5300, 0x08, 0, 0}, {0x5301, 0x30, 0, 0}, 
	{0x5302, 0x10, 0, 0}, {0x5303, 0x00, 0, 0}, {0x5304, 0x08, 0, 0},  
	{0x5305, 0x30, 0, 0}, {0x5306, 0x08, 0, 0}, {0x5307, 0x16, 0, 0}, 
	{0x5309, 0x08, 0, 0}, {0x530a, 0x30, 0, 0}, {0x530b, 0x04, 0, 0}, 
	{0x530c, 0x06, 0, 0}, {0x5480, 0x01, 0, 0}, {0x5481, 0x08, 0, 0},  
	{0x5482, 0x14, 0, 0}, {0x5483, 0x28, 0, 0}, {0x5484, 0x51, 0, 0}, 
	{0x5485, 0x65, 0, 0}, {0x5486, 0x71, 0, 0}, {0x5487, 0x7d, 0, 0}, 
	{0x5488, 0x87, 0, 0}, {0x5489, 0x91, 0, 0}, {0x548a, 0x9a, 0, 0}, 
	{0x548b, 0xaa, 0, 0}, {0x548c, 0xb8, 0, 0}, {0x548d, 0xcd, 0, 0}, 
	{0x548e, 0xdd, 0, 0}, {0x548f, 0xea, 0, 0}, {0x5490, 0x1d, 0, 0}, 
	{0x5580, 0x02, 0, 0}, {0x5583, 0x40, 0, 0}, {0x5584, 0x10, 0, 0}, 
	{0x5589, 0x10, 0, 0}, {0x558a, 0x00, 0, 0}, {0x558b, 0xf8, 0, 0}, 
	{0x5800, 0x23, 0, 0}, {0x5801, 0x14, 0, 0}, {0x5802, 0x0f, 0, 0}, 
	{0x5803, 0x0f, 0, 0}, {0x5804, 0x12, 0, 0}, {0x5805, 0x26, 0, 0}, 
	{0x5806, 0x0c, 0, 0}, {0x5807, 0x08, 0, 0}, {0x5808, 0x05, 0, 0},  
	{0x5809, 0x05, 0, 0}, {0x580a, 0x08, 0, 0}, {0x580b, 0x0d, 0, 0}, 
	{0x580c, 0x08, 0, 0}, {0x580d, 0x03, 0, 0}, {0x580e, 0x00, 0, 0}, 
	{0x580f, 0x00, 0, 0}, {0x5810, 0x03, 0, 0}, {0x5811, 0x09, 0, 0}, 
	{0x5812, 0x07, 0, 0}, {0x5813, 0x03, 0, 0}, {0x5814, 0x00, 0, 0}, 
	{0x5815, 0x01, 0, 0}, {0x5816, 0x03, 0, 0}, {0x5817, 0x08, 0, 0}, 
	{0x5818, 0x0d, 0, 0}, {0x5819, 0x08, 0, 0}, {0x581a, 0x05, 0, 0}, 
	{0x581b, 0x06, 0, 0}, {0x581c, 0x08, 0, 0}, {0x581d, 0x0e, 0, 0}, 
	{0x581e, 0x29, 0, 0}, {0x581f, 0x17, 0, 0}, {0x5820, 0x11, 0, 0}, 
	{0x5821, 0x11, 0, 0}, {0x5822, 0x15, 0, 0}, {0x5823, 0x28, 0, 0}, 
	{0x5824, 0x46, 0, 0}, {0x5825, 0x26, 0, 0}, {0x5826, 0x08, 0, 0}, 
	{0x5827, 0x26, 0, 0}, {0x5828, 0x64, 0, 0}, {0x5829, 0x26, 0, 0}, 
	{0x582a, 0x24, 0, 0}, {0x582b, 0x22, 0, 0}, {0x582c, 0x24, 0, 0}, 
	{0x582d, 0x24, 0, 0}, {0x582e, 0x06, 0, 0}, {0x582f, 0x22, 0, 0}, 
	{0x5830, 0x40, 0, 0}, {0x5831, 0x42, 0, 0}, {0x5832, 0x24, 0, 0}, 
	{0x5833, 0x26, 0, 0}, {0x5834, 0x24, 0, 0}, {0x5835, 0x22, 0, 0}, 
	{0x5836, 0x22, 0, 0}, {0x5837, 0x26, 0, 0}, {0x5838, 0x44, 0, 0}, 
	{0x5839, 0x24, 0, 0}, {0x583a, 0x26, 0, 0}, {0x583b, 0x28, 0, 0}, 
	{0x583c, 0x42, 0, 0}, {0x583d, 0xce, 0, 0}, {0x5025, 0x00, 0, 0}, 
	{0x3a0f, 0x30, 0, 0}, {0x3a10, 0x28, 0, 0}, {0x3a1b, 0x30, 0, 0}, 
	{0x3a1e, 0x26, 0, 0}, {0x3a11, 0x60, 0, 0}, {0x3a1f, 0x14, 0, 0}, 
	{0x3008, 0x02, 0, 0},
#endif


#ifdef HDMI_720_480

        {0x3103, 0x11, 0, 0}, {0x3008, 0x82, 0, 0}, {0x3008, 0x42, 0, 0},
        {0x3103, 0x03, 0, 0}, {0x3017, 0x00, 0, 0}, {0x3018, 0x00, 0, 0},
        {0x3034, 0x18, 0, 0}, {0x3035, 0x11, 0, 0}, {0x3036, 0x56, 0, 0},
        {0x3037, 0x14, 0, 0}, {0x3108, 0x01, 0, 0}, {0x3630, 0x36, 0, 0},
        {0x3631, 0x0e, 0, 0}, {0x3632, 0xe2, 0, 0}, {0x3633, 0x12, 0, 0},
        {0x3621, 0xe0, 0, 0}, {0x3704, 0xa0, 0, 0}, {0x3703, 0x5a, 0, 0},
        {0x3715, 0x78, 0, 0}, {0x3717, 0x01, 0, 0}, {0x370b, 0x60, 0, 0},
        {0x3705, 0x1a, 0, 0}, {0x3905, 0x02, 0, 0}, {0x3906, 0x10, 0, 0},
        {0x3901, 0x0a, 0, 0}, {0x3731, 0x12, 0, 0}, {0x3600, 0x08, 0, 0},
        {0x3601, 0x33, 0, 0}, {0x302d, 0x60, 0, 0}, {0x3620, 0x52, 0, 0},
        {0x371b, 0x20, 0, 0}, {0x471c, 0x50, 0, 0}, {0x3a13, 0x43, 0, 0},
        {0x3a18, 0x00, 0, 0}, {0x3a19, 0xf8, 0, 0}, {0x3635, 0x13, 0, 0},
        {0x3636, 0x03, 0, 0}, {0x3634, 0x40, 0, 0}, {0x3622, 0x01, 0, 0},
        {0x3c01, 0x34, 0, 0}, {0x3c04, 0x28, 0, 0}, {0x3c05, 0x98, 0, 0},
        {0x3c06, 0x00, 0, 0}, {0x3c07, 0x07, 0, 0}, {0x3c08, 0x00, 0, 0},
        {0x3c09, 0x1c, 0, 0}, {0x3c0a, 0x9c, 0, 0}, {0x3c0b, 0x40, 0, 0},
        {0x3820, 0x40, 0, 0}, {0x3821, 0x00, 0, 0}, {0x3814, 0x11, 0, 0},
        {0x3815, 0x11, 0, 0}, {0x3800, 0x01, 0, 0}, {0x3801, 0x50, 0, 0},
        {0x3802, 0x01, 0, 0}, {0x3803, 0xb2, 0, 0}, {0x3804, 0x04, 0, 0},
        {0x3805, 0x3f, 0, 0}, {0x3806, 0x03, 0, 0}, {0x3807, 0x99, 0, 0},
        {0x3808, 0x02, 0, 0}, {0x3809, 0xd0, 0, 0}, {0x380a, 0x01, 0, 0},
        {0x380b, 0xe0, 0, 0}, {0x380c, 0x06, 0, 0}, {0x380d, 0xbd, 0, 0},
        {0x380e, 0x03, 0, 0}, {0x380f, 0xe8, 0, 0}, {0x3810, 0x00, 0, 0},
        {0x3811, 0x10, 0, 0}, {0x3812, 0x00, 0, 0}, {0x3813, 0x04, 0, 0},
        {0x3618, 0x04, 0, 0}, {0x3612, 0x2b, 0, 0}, {0x3708, 0x63, 0, 0},
        {0x3709, 0x12, 0, 0}, {0x370c, 0x00, 0, 0}, {0x3a02, 0x07, 0, 0},
        {0x3a03, 0xb0, 0, 0}, {0x3a08, 0x01, 0, 0}, {0x3a09, 0x27, 0, 0},
        {0x3a0a, 0x00, 0, 0}, {0x3a0b, 0xf6, 0, 0}, {0x3a0e, 0x06, 0, 0},
        {0x3a0d, 0x08, 0, 0}, {0x3a14, 0x07, 0, 0}, {0x3a15, 0xb0, 0, 0},
        {0x4001, 0x02, 0, 0}, {0x4004, 0x06, 0, 0}, {0x4050, 0x6e, 0, 0},
        {0x4051, 0x8f, 0, 0}, {0x3000, 0x00, 0, 0}, {0x3002, 0x1c, 0, 0},
        {0x3004, 0xff, 0, 0}, {0x3006, 0xc3, 0, 0}, {0x300e, 0x45, 0, 0},
        {0x302e, 0x08, 0, 0}, {0x4300, 0x20, 0, 0}, {0x501f, 0x01, 0, 0},
        {0x5684, 0x0a, 0, 0}, {0x5685, 0x20, 0, 0}, {0x5686, 0x07, 0, 0},
        {0x5687, 0x98, 0, 0}, {0x440e, 0x00, 0, 0}, {0x4837, 0x16, 0, 0},
        {0x5000, 0xf7, 0, 0}, {0x5001, 0x03, 0, 0}, {0x3a0f, 0x36, 0, 0},
        {0x3a10, 0x2e, 0, 0}, {0x3a1b, 0x38, 0, 0}, {0x3a1e, 0x2c, 0, 0},
        {0x3a11, 0x70, 0, 0}, {0x3a1f, 0x18, 0, 0}, {0x3008, 0x02, 0, 0},
#endif 
	/* Color Pattern test */ //{0x503d, 0x80, 0, 0},//{0x4741, 0x00, 0, 0}, 
};

enum ov5640_mode {
	ov5640_mode_MIN = 0,
	ov5640_mode_VGA_640_480 = 0,
	ov5640_mode_QVGA_320_240 = 1,
	ov5640_mode_NTSC_720_480 = 2,
	ov5640_mode_PAL_720_576 = 3,
	ov5640_mode_720P_1280_720 = 4,
	ov5640_mode_1080P_1920_1080 = 5,
	ov5640_mode_QSXGA_2592_1944 = 6,
	ov5640_mode_QCIF_176_144 = 7,
	ov5640_mode_XGA_1024_768 = 8,
	ov5640_mode_MAX = 8,
	ov5640_mode_INIT = 0xff, /*only for sensor init*/
};

enum ov5640_frame_rate {
	ov5640_15_fps,
	ov5640_30_fps
};



static s32 ov5640_read_reg(u16 reg, u8 *val)
{
	int ret;
	ret = i2c_read(OV5640_I2C_SLAVE_ADDR, reg, 2, (unsigned char *)val, 1);
	//printf("\t\treg=0x%x\t\tdata=%x\n",reg,*val);
	if (ret != 0) {
		printf("Error while reading register %#04x\n", reg);
		return -1;
	}
	return val;
}

static s32 ov5640_write_reg(u16 reg, u8 val)
{
	return i2c_write(OV5640_I2C_SLAVE_ADDR,reg,2,(unsigned char *)&val,1);
}

int OV5640_set_AE_target(int target)
{
	/* stable in high */
	int fast_high, fast_low;
	AE_low = target * 23 / 25;	/* 0.92 */
	AE_high = target * 27 / 25;	/* 1.08 */

	fast_high = AE_high<<1;
	if (fast_high > 255)
		fast_high = 255;

	fast_low = AE_low >> 1;

	ov5640_write_reg(0x3a0f, AE_high);
	ov5640_write_reg(0x3a10, AE_low);
	ov5640_write_reg(0x3a1b, AE_high);
	ov5640_write_reg(0x3a1e, AE_low);
	ov5640_write_reg(0x3a11, fast_high);
	ov5640_write_reg(0x3a1f, fast_low);

	return 0;
}

int OV5640_get_light_frequency(void)
{
	/* get banding filter value */
	int temp, temp1, light_frequency = 0;
	u8 tmp;

	temp = ov5640_read_reg(0x3c01, &tmp);

	if (temp & 0x80) {
		/* manual */
		temp1 = ov5640_read_reg(0x3c00, &tmp);
		if (temp1 & 0x04) {
			/* 50Hz */
			light_frequency = 50;
		} else {
			/* 60Hz */
			light_frequency = 60;
		}
	} else {
		/* auto */
		temp1 = ov5640_read_reg(0x3c0c, &tmp);
		if (temp1 & 0x01) {
			/* 50Hz */
			light_frequency = 50;
		} else {
			/* 60Hz */
		}
	}
	return light_frequency;
}

int OV5640_get_sysclk(void)
{
	 /* calculate sysclk */
	int temp1, temp2;
	int Multiplier, PreDiv, VCO, SysDiv, Pll_rdiv, Bit_div2x = 1, sclk_rdiv, sysclk;
	u8 temp;

	int sclk_rdiv_map[] = {1, 2, 4, 8};

	temp1 = ov5640_read_reg(0x3034, &temp);
	temp2 = temp1 & 0x0f;
	if (temp2 == 8 || temp2 == 10) {
		Bit_div2x = temp2 / 2;
	}

	temp1 = ov5640_read_reg(0x3035, &temp);
	SysDiv = temp1>>4;
	if (SysDiv == 0) {
	       SysDiv = 16;
	}

	temp1 = ov5640_read_reg(0x3036, &temp);
	Multiplier = temp1;

	temp1 = ov5640_read_reg(0x3037, &temp);
	PreDiv = temp1 & 0x0f;
	Pll_rdiv = ((temp1 >> 4) & 0x01) + 1;

	temp1 = ov5640_read_reg(0x3108, &temp);
	temp2 = temp1 & 0x03;
	sclk_rdiv = sclk_rdiv_map[temp2];
	VCO = XVCLK * Multiplier / PreDiv;
	sysclk = VCO / SysDiv / Pll_rdiv * 2 / Bit_div2x / sclk_rdiv;
	return sysclk;
}

int OV5640_get_HTS(void)
{
	 /* read HTS from register settings */
	int HTS;
	u8 temp;

	HTS = ov5640_read_reg(0x380c, &temp);
	HTS = (HTS<<8) + ov5640_read_reg(0x380d, &temp);

	return HTS;
}

int OV5640_get_VTS(void)
{
	 /* read VTS from register settings */
	int VTS;
	u8 temp;

	VTS = ov5640_read_reg(0x380e, &temp);/* total vertical size[15:8] high byte */

	VTS = (VTS<<8) + ov5640_read_reg(0x380f, &temp);

	return VTS;
}

void OV5640_set_bandingfilter(void)
{
	int preview_VTS;
	int band_step60, max_band60, band_step50, max_band50;

	/* read preview PCLK */
	preview_sysclk = OV5640_get_sysclk();
	/* read preview HTS */
	preview_HTS = OV5640_get_HTS();

	/* read preview VTS */
	preview_VTS = OV5640_get_VTS();

	/* calculate banding filter */
	/* 60Hz */
	band_step60 = preview_sysclk * 100/preview_HTS * 100/120;
	ov5640_write_reg(0x3a0a, (band_step60 >> 8));
	ov5640_write_reg(0x3a0b, (band_step60 & 0xff));

	max_band60 = (int)((preview_VTS-4)/band_step60);
	ov5640_write_reg(0x3a0d, max_band60);

	/* 50Hz */
	band_step50 = preview_sysclk * 100/preview_HTS;
	ov5640_write_reg(0x3a08, (band_step50 >> 8));
	ov5640_write_reg(0x3a09, (band_step50 & 0xff));

	max_band50 = (int)((preview_VTS-4)/band_step50);
	ov5640_write_reg(0x3a0e, max_band50);
}

static void ov5640_set_virtual_channel(int channel)
{
	u8 channel_id;

	ov5640_read_reg(0x4814, &channel_id);
	channel_id &= ~(3 << 6);
	ov5640_write_reg(0x4814, channel_id | (channel << 6));
}

void OV5640_stream_on(void)
{	
        int mipi_reg,mask=0;
	ov5640_write_reg(0x4202, 0x00);

#if 0        
	mipi_reg = mipi_csi_read(CSI2_PHY_STATE);
        printf("CSI PHY status in stream on = 0x%x \n", mipi_reg);
        mask = (1 << PHY_RXCLKACTIVEHS);
       	while(!(mask & mipi_csi_read(CSI2_PHY_STATE)));//can Hang
       	printf("the clock lane is actively receiving a DDR clock after stream on\n");
#endif
}
void OV5640_stream_off(void)
{
	ov5640_write_reg(0x4202, 0x0f);
}

static int ov5640_init_mode(enum ov5640_frame_rate frame_rate,
			    enum ov5640_mode mode)
{
	struct reg_value *pModeSetting = NULL;
	signed int i = 0;
	signed int iModeSettingArySize = 0;
	register u32 Delay_ms = 0;
	register u16 RegAddr = 0;
	register u8 Mask = 0;
	register u8 Val = 0;
	u8 RegVal = 0;
	int retval,mipi_reg,mask = 0;
	pModeSetting = ov5640_init_setting_30fps_VGA;
	iModeSettingArySize = ARRAY_SIZE(ov5640_init_setting_30fps_VGA);

	
	for (i = 0; i < iModeSettingArySize; ++i, ++pModeSetting) {
		Delay_ms = pModeSetting->u32Delay_ms;
		RegAddr = pModeSetting->u16RegAddr;
		Val = pModeSetting->u8Val;
		Mask = pModeSetting->u8Mask;
		if (Mask) {
			retval = ov5640_read_reg(RegAddr, &RegVal);
			if (retval < 0){
				printf("I2C read error\n");
				return 1;
			}
			RegVal &= ~(u8)Mask;
			Val &= Mask;
			Val |= RegVal;
		}

		retval = ov5640_write_reg(RegAddr, Val);
		if (retval < 0){
                        printf("I2C write error\n");
                        return 1;
                 }
		if (Delay_ms)
			mdelay(Delay_ms);
	}

//	OV5640_set_AE_target(AE_Target);
//	OV5640_get_light_frequency();
//	OV5640_set_bandingfilter();
//	ov5640_set_virtual_channel(0);
	udelay(10000);
		
	/* printf("Going to read the clock and data lane should in stop state\n"); */
        /* printf("CSI PHY status = 0x%x \n", mipi_csi_read(CSI2_PHY_STATE));  //can Hang */
	
	OV5640_stream_off();
	//OV5640_stream_on();
	
	return retval;
} 


int do_camera_init(cmd_tbl_t *cmdtp, int flag, int argc, char * const argv[])
{
	int i,ret=0,retval;
	u8 chip_id_high, chip_id_low;
	enum ov5640_frame_rate frame_rate;
	int iModeSettingArySize;
		
	i2c_set_bus_num(OV5640_CAMERA_I2C_BUS_NO);
        writel(0xF0000000, TZASC2_BASE+0x108);
        writel(0xF0000000, TZASC1_BASE+0x108);
        writel(0xF0000000, TZASC0_BASE+0x108);

//	ov5640_write_reg(0x4800, 0x24);
//	ov5640_write_reg(0x3019, 0x70);
	/* Initalise MIPI CSI Controller */
	udelay(10000);

	/* printf("Going to call MIPI CSI init\n"); */
	mipi_csi_init();

	i2c_set_bus_num(OV5640_CAMERA_I2C_BUS_NO);
	/* Read ID of OV5640 */
	retval = ov5640_read_reg(OV5640_CHIP_ID_HIGH_BYTE, &chip_id_high);
	printf("Info: ov5640 chip id high byte: %x\n",chip_id_high);
	if (retval < 0 || chip_id_high != 0x56) {
		printf("ERROR: cannot find camera %x\n",chip_id_high);
		return -1;
	}
	retval = ov5640_read_reg(OV5640_CHIP_ID_LOW_BYTE, &chip_id_low);
	printf("Info: ov5640 chip id low byte: %x\n",chip_id_low);
	if (retval < 0 || chip_id_low != 0x40) {
		printf("ERROR: cannot find camera %x\n",chip_id_low);
		return -1;
	}

	frame_rate = ov5640_30_fps;
	ret = ov5640_init_mode(frame_rate, ov5640_mode_INIT);
	if(ret < 0){
		printf("ERROR in Initialisation\n");
		return 1;
	}
	printf("Cam init is successfull\n");
	return ret;
}

int do_camera_detect(cmd_tbl_t *cmdtp, int flag, int argc, char * const argv[])
{
    int ret=0,retval;
    u8 chip_id_high, chip_id_low;

        i2c_set_bus_num(OV5640_CAMERA_I2C_BUS_NO);
        /* Read ID of OV5640 */
        retval = ov5640_read_reg(OV5640_CHIP_ID_HIGH_BYTE, &chip_id_high);
        if (retval < 0 || chip_id_high != 0x56) {
                printf("ERROR: cannot find camera %x\n",chip_id_high);
                return -1;
        }
        retval = ov5640_read_reg(OV5640_CHIP_ID_LOW_BYTE, &chip_id_low);
        if (retval < 0 || chip_id_low != 0x40) {
                printf("ERROR: cannot find camera %x\n",chip_id_low);
                return -1;
        }
    
        printf("camera device id(higher byte): 0x%x\n",chip_id_high);
        printf("camera device id(lower byte): 0x%x\n",chip_id_low);
        return 0;
}

U_BOOT_CMD(
        caminit, 2, 1, do_camera_init,
        "Initialise OV5640 Image Sensor",
	"No parameter needed"
        );

U_BOOT_CMD(
        cam_detect, 2, 1, do_camera_detect,
        "Detect OV5640 Image Sensor",
	"No parameter needed"
        );
