#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# See file CREDITS for list of people who contributed to this
# project.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307 USA
#

include $(TOPDIR)/config.mk

LIB	:= $(obj)libgpu_pp2.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_FAxx_check_0_a.o m400_pp_2_FAxx_check_0_b.o m400_pp_2_FAxx_mem_0.o m400_pp_2_FAxx_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_FBxx_check_0_a.o m400_pp_2_FBxx_check_0_b.o m400_pp_2_FBxx_mem_0.o m400_pp_2_FBxx_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_FLSxx_check_0_a.o m400_pp_2_FLSxx_check_0_b.o m400_pp_2_FLSxx_mem_0.o m400_pp_2_FLSxx_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_FLxx_check_0_a.o m400_pp_2_FLxx_check_0_b.o m400_pp_2_FLxx_mem_0.o m400_pp_2_FLxx_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_FNxx_check_0_a.o m400_pp_2_FNxx_check_0_b.o m400_pp_2_FNxx_mem_0.o m400_pp_2_FNxx_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_FTxx_check_0_a.o m400_pp_2_FTxx_check_0_b.o m400_pp_2_FTxx_mem_0.o m400_pp_2_FTxx_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_FVxx_check_0_a.o m400_pp_2_FVxx_check_0_b.o m400_pp_2_FVxx_mem_0.o m400_pp_2_FVxx_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_GCxx04_check_0_a.o m400_pp_2_GCxx04_check_0_b.o m400_pp_2_GCxx04_mem_0.o m400_pp_2_GCxx04_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_GCxx07_check_0_a.o m400_pp_2_GCxx07_check_0_b.o m400_pp_2_GCxx07_mem_0.o m400_pp_2_GCxx07_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_GFxx03_check_0_a.o m400_pp_2_GFxx03_check_0_b.o m400_pp_2_GFxx03_mem_0.o m400_pp_2_GFxx03_run.o 

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_GFxx29_check_0_a.o m400_pp_2_GFxx29_check_0_b.o m400_pp_2_GFxx29_mem_0.o m400_pp_2_GFxx29_run.o 

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_GFxx39_check_0_a.o m400_pp_2_GFxx39_check_0_b.o m400_pp_2_GFxx39_mem_0.o m400_pp_2_GFxx39_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_GFxx42_check_0_a.o m400_pp_2_GFxx42_check_0_b.o m400_pp_2_GFxx42_mem_0.o m400_pp_2_GFxx42_run.o 

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_GFxx49_check_0_a.o m400_pp_2_GFxx49_check_0_b.o m400_pp_2_GFxx49_mem_0.o m400_pp_2_GFxx49_run.o
 
COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_GFxx56_check_0_a.o m400_pp_2_GFxx56_check_0_b.o m400_pp_2_GFxx56_mem_0.o m400_pp_2_GFxx56_run.o 

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_GLxx05_check_0_a.o m400_pp_2_GLxx05_check_0_b.o m400_pp_2_GLxx05_mem_0.o m400_pp_2_GLxx05_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_GLxx06_check_0_a.o m400_pp_2_GLxx06_check_0_b.o m400_pp_2_GLxx06_mem_0.o m400_pp_2_GLxx06_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_GLxx08_check_0_a.o m400_pp_2_GLxx08_check_0_b.o m400_pp_2_GLxx08_mem_0.o m400_pp_2_GLxx08_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_GLxx09_check_0_a.o m400_pp_2_GLxx09_check_0_b.o m400_pp_2_GLxx09_mem_0.o m400_pp_2_GLxx09_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_ibi01_check_0_a.o m400_pp_2_ibi01_check_0_b.o m400_pp_2_ibi01_check_0_c.o m400_pp_2_ibi01_check_0_d.o m400_pp_2_ibi01_check_0_e.o m400_pp_2_ibi01_check_0_f.o m400_pp_2_ibi01_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_ibi02_check_0_a.o m400_pp_2_ibi02_check_0_b.o m400_pp_2_ibi02_check_0_c.o m400_pp_2_ibi02_check_0_d.o m400_pp_2_ibi02_check_0_e.o m400_pp_2_ibi02_check_0_f.o m400_pp_2_ibi02_check_0_g.o m400_pp_2_ibi02_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_ibi03_check_0_a.o m400_pp_2_ibi03_check_0_b.o m400_pp_2_ibi03_check_0_c.o m400_pp_2_ibi03_check_0_d.o m400_pp_2_ibi03_check_0_e.o m400_pp_2_ibi03_check_0_f.o m400_pp_2_ibi03_check_0_g.o m400_pp_2_ibi03_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_ibi04_check_0_a.o m400_pp_2_ibi04_check_0_b.o m400_pp_2_ibi04_check_0_c.o m400_pp_2_ibi04_check_0_d.o m400_pp_2_ibi04_check_0_e.o m400_pp_2_ibi04_check_0_f.o m400_pp_2_ibi04_check_0_g.o m400_pp_2_ibi04_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_ibi05_check_0_a.o m400_pp_2_ibi05_check_0_b.o m400_pp_2_ibi05_check_0_c.o m400_pp_2_ibi05_check_0_d.o m400_pp_2_ibi05_check_0_e.o m400_pp_2_ibi05_check_0_f.o m400_pp_2_ibi05_check_0_g.o m400_pp_2_ibi05_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_ibi06_check_0_a.o m400_pp_2_ibi06_check_0_b.o m400_pp_2_ibi06_check_0_c.o m400_pp_2_ibi06_check_0_d.o m400_pp_2_ibi06_check_0_e.o m400_pp_2_ibi06_check_0_f.o m400_pp_2_ibi06_check_0_g.o m400_pp_2_ibi06_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_ibi07_check_0_a.o m400_pp_2_ibi07_check_0_b.o m400_pp_2_ibi07_check_0_c.o m400_pp_2_ibi07_check_0_d.o m400_pp_2_ibi07_check_0_e.o m400_pp_2_ibi07_check_0_f.o m400_pp_2_ibi07_check_0_g.o m400_pp_2_ibi07_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_ibi08_check_0_a.o m400_pp_2_ibi08_check_0_b.o m400_pp_2_ibi08_check_0_c.o m400_pp_2_ibi08_check_0_d.o m400_pp_2_ibi08_check_0_e.o m400_pp_2_ibi08_check_0_f.o m400_pp_2_ibi08_check_0_g.o m400_pp_2_ibi08_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_ibi09_check_0_a.o m400_pp_2_ibi09_check_0_b.o m400_pp_2_ibi09_check_0_c.o m400_pp_2_ibi09_check_0_d.o m400_pp_2_ibi09_check_0_e.o m400_pp_2_ibi09_check_0_f.o m400_pp_2_ibi09_check_0_g.o m400_pp_2_ibi09_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_ibr01_check_0_a.o m400_pp_2_ibr01_check_0_b.o m400_pp_2_ibr01_check_0_c.o m400_pp_2_ibr01_check_0_d.o m400_pp_2_ibr01_check_0_e.o m400_pp_2_ibr01_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_ibr02_check_0_a.o m400_pp_2_ibr02_check_0_b.o m400_pp_2_ibr02_check_0_c.o m400_pp_2_ibr02_check_0_d.o m400_pp_2_ibr02_check_0_e.o  m400_pp_2_ibr02_check_0_f.o m400_pp_2_ibr02_check_0_g.o m400_pp_2_ibr02_check_0_h.o m400_pp_2_ibr02_check_0_i.o m400_pp_2_ibr02_check_0_j.o m400_pp_2_ibr02_check_0_k.o m400_pp_2_ibr02_check_0_l.o m400_pp_2_ibr02_check_0_m.o m400_pp_2_ibr02_check_0_n.o m400_pp_2_ibr02_check_0_o.o m400_pp_2_ibr02_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_ibr03_check_0_a.o m400_pp_2_ibr03_check_0_b.o m400_pp_2_ibr03_check_0_c.o m400_pp_2_ibr03_check_0_d.o m400_pp_2_ibr03_check_0_e.o  m400_pp_2_ibr03_check_0_f.o m400_pp_2_ibr03_check_0_g.o m400_pp_2_ibr03_check_0_h.o m400_pp_2_ibr03_check_0_i.o m400_pp_2_ibr03_check_0_j.o m400_pp_2_ibr03_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_IIBF02_check_0_a.o m400_pp_2_IIBF02_check_0_b.o m400_pp_2_IIBF02_check_1_c.o m400_pp_2_IIBF02_check_1_d.o m400_pp_2_IIBF02_mem_0.o m400_pp_2_IIBF02_mem_1.o m400_pp_2_IIBF02_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_IIBF05_check_0_a.o m400_pp_2_IIBF05_check_0_b.o m400_pp_2_IIBF05_check_1_c.o m400_pp_2_IIBF05_check_1_d.o m400_pp_2_IIBF05_mem_0.o m400_pp_2_IIBF05_mem_1.o m400_pp_2_IIBF05_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_IWCx11_check_0_a.o m400_pp_2_IWCx11_check_0_b.o m400_pp_2_IWCx11_mem_0.o m400_pp_2_IWCx11_run.o

COBJS-$(CONFIG_MALIGPU_PP2) +=m400_pp_2_IWGCxx_check_0_a.o m400_pp_2_IWGCxx_check_0_b.o m400_pp_2_IWGCxx_mem_0.o m400_pp_2_IWGCxx_run.o

COBJS	:= $(COBJS-y)
SRCS	:= $(COBJS:.o=.c)
OBJS	:= $(addprefix $(obj),$(COBJS))

all:	$(LIB)

$(LIB):	$(obj).depend $(OBJS)
	$(call cmd_link_o_target, $(OBJS))

#########################################################################

# defines $(obj).depend target
include $(SRCTREE)/rules.mk

sinclude $(obj).depend

#########################################################################
